import {test, expect} from "./fixture.js";
import {api} from "../e2e/environment.js";
import {backendModule} from "./environment.js";
import {randomUUID} from "node:crypto";

const endpoint = `${api}/accounts/preferences/homework-templates`;
test("personal templates persist, isolate accounts, compare revisions atomically and enforce the concurrent limit", async ({classroom, request}) => {
  const headers = {Authorization: `Bearer ${classroom.credentials.accessToken}`};
  const input = {name: "练习册", title: "第〔页码〕页", content: "完成〔题号〕", dueAt: "old", accountId: "other"};
  expect((await request.get(endpoint)).status()).toBe(401);
  const response = await request.post(endpoint, {headers, data: input});
  expect(response.status()).toBe(201);
  const row = (await response.json()).data;
  expect(row).toEqual({id: expect.any(String), name: input.name, title: input.title, content: input.content, revision: 1});
  const account = await classroom.prisma.account.create({data: {provider: "school-local", providerId: randomUUID(), name: "另一位教师"}});
  const {generateTokenPair} = await backendModule("utils/tokenManager.js");
  const other = {Authorization: `Bearer ${(await generateTokenPair(account)).accessToken}`};
  expect((await (await request.get(endpoint, {headers: other})).json()).data).toEqual([]);
  expect((await request.put(`${endpoint}/${row.id}`, {headers: other, data: {...input, expectedRevision: 1}})).status()).toBe(409);
  expect((await request.delete(`${endpoint}/${row.id}`, {headers: other, data: {expectedRevision: 1}})).status()).toBe(409);
  expect((await request.put(`${endpoint}/${row.id}`, {headers, data: input})).status()).toBe(428);
  const competing = await Promise.all(["甲修改", "乙修改"].map(name => request.put(`${endpoint}/${row.id}`, {headers, data: {...input, name, expectedRevision: 1}})));
  expect(competing.map(result => result.status()).sort()).toEqual([200, 409]);
  expect((await request.delete(`${endpoint}/${row.id}`, {headers, data: {expectedRevision: 1}})).status()).toBe(409);
  const stored = await classroom.prisma.accountPreference.findUnique({where: {accountId_key: {accountId: classroom.account.id, key: `homework-template:${row.id}`}}});
  expect(stored.value.revision).toBe(2);
  await classroom.prisma.accountPreference.createMany({data: Array.from({length: 48}, () => ({accountId: classroom.account.id, key: `homework-template:${randomUUID()}`, value: {...input, revision: 1}}))});
  const capped = await Promise.all([1, 2].map(() => request.post(endpoint, {headers, data: input})));
  expect(capped.map(result => result.status()).sort()).toEqual([201, 409]);
  expect((await (await request.get(endpoint, {headers})).json()).data).toHaveLength(50);
  expect((await request.delete(`${endpoint}/${row.id}`, {headers, data: {expectedRevision: 2}})).status()).toBe(200);
});

test("teacher templates sync across browsers, preserve editor targets/times and retain conflicting edits", async ({classroom, request}) => {
  const a = await classroom.open("teacher");
  const composer = a.page.locator(".publication-composer");
  await composer.getByRole("textbox", {name: "正文 正文", exact: true}).fill("原有正文");
  await composer.getByRole("button", {name: "个人作业模板", exact: true}).click();
  const templates = a.page.locator(".homework-templates");
  await templates.getByRole("button", {name: "新建模板", exact: true}).click();
  await templates.getByLabel("模板名称", {exact: true}).fill("每天练习");
  await templates.getByLabel("模板标题", {exact: true}).fill("第〔页码〕页");
  await templates.getByLabel("模板正文", {exact: true}).fill("完成〔页码〕页的〔题号〕题");
  await templates.getByRole("button", {name: "保存模板", exact: true}).click();
  await expect(templates.locator(".template-item")).toHaveCount(1);
  const b = await classroom.open("teacher");
  await b.page.getByRole("button", {name: "个人作业模板", exact: true}).click();
  const remote = b.page.locator(".homework-templates");
  await expect(remote).toContainText("每天练习");
  await remote.getByRole("button", {name: "编辑", exact: true}).click();
  await remote.getByLabel("模板正文", {exact: true}).fill("另一电脑尚未保存的输入");
  await templates.getByRole("button", {name: "编辑", exact: true}).click();
  await templates.getByLabel("模板名称", {exact: true}).fill("每天练习新版");
  await templates.getByRole("button", {name: "保存模板", exact: true}).click();
  await remote.getByRole("button", {name: "保存模板", exact: true}).click();
  await expect(remote).toContainText("模板已被修改或删除");
  await expect(remote.getByLabel("模板正文", {exact: true})).toHaveValue("另一电脑尚未保存的输入");
  const snapshot = () => composer.locator("input").evaluateAll(inputs => inputs.filter(input => !input.closest(".v-text-field")?.textContent.includes("标题（可选）")).map(input => [input.type, input.value]));
  const before = await snapshot();
  await templates.getByRole("button", {name: "填写使用", exact: true}).click();
  await expect(templates.getByRole("button", {name: "套用到编辑器", exact: true})).toBeDisabled();
  await templates.getByLabel("填写：页码", {exact: true}).fill("12");
  await templates.getByLabel("填写：题号", {exact: true}).fill("1—5");
  await templates.getByRole("button", {name: "套用到编辑器", exact: true}).click();
  await a.page.getByRole("button", {name: "取消", exact: true}).last().click();
  await expect(composer.getByRole("textbox", {name: "正文 正文", exact: true})).toHaveValue("原有正文");
  await templates.getByRole("button", {name: "套用到编辑器", exact: true}).click();
  await a.page.getByRole("button", {name: "替换内容", exact: true}).click();
  await expect(templates).not.toBeVisible();
  await expect(composer.getByRole("textbox", {name: "正文 正文", exact: true})).toHaveValue("完成12页的1—5题");
  expect(await snapshot()).toEqual(before);
  expect(await classroom.rows()).toEqual([]); // Applying is not publishing.
  const headers = {Authorization: `Bearer ${classroom.credentials.accessToken}`};
  expect((await (await request.get(endpoint, {headers})).json()).data[0].name).toBe("每天练习新版");
  expect([...a.errors, ...b.errors]).toEqual([]);
});
